//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmevClient.SmevServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageType", Namespace="http://smev.gosuslugi.ru/rev120315")]
    [System.SerializableAttribute()]
    public partial class MessageType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private SmevClient.SmevServiceReference.orgExternalType SenderField;
        
        private SmevClient.SmevServiceReference.orgExternalType RecipientField;
        
        private SmevClient.SmevServiceReference.orgExternalType OriginatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SmevClient.SmevServiceReference.TypeCodeType TypeCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SmevClient.SmevServiceReference.StatusType StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExchangeTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestIdRefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OriginRequestIdRefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CaseNumberField;
        
        private SmevClient.SmevServiceReference.SubMessage[] SubMessagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TestMsgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OKTMOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public SmevClient.SmevServiceReference.orgExternalType Sender {
            get {
                return this.SenderField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderField, value) != true)) {
                    this.SenderField = value;
                    this.RaisePropertyChanged("Sender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public SmevClient.SmevServiceReference.orgExternalType Recipient {
            get {
                return this.RecipientField;
            }
            set {
                if ((object.ReferenceEquals(this.RecipientField, value) != true)) {
                    this.RecipientField = value;
                    this.RaisePropertyChanged("Recipient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public SmevClient.SmevServiceReference.orgExternalType Originator {
            get {
                return this.OriginatorField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginatorField, value) != true)) {
                    this.OriginatorField = value;
                    this.RaisePropertyChanged("Originator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public SmevClient.SmevServiceReference.TypeCodeType TypeCode {
            get {
                return this.TypeCodeField;
            }
            set {
                if ((this.TypeCodeField.Equals(value) != true)) {
                    this.TypeCodeField = value;
                    this.RaisePropertyChanged("TypeCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public SmevClient.SmevServiceReference.StatusType Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string ExchangeType {
            get {
                return this.ExchangeTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ExchangeTypeField, value) != true)) {
                    this.ExchangeTypeField = value;
                    this.RaisePropertyChanged("ExchangeType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string RequestIdRef {
            get {
                return this.RequestIdRefField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestIdRefField, value) != true)) {
                    this.RequestIdRefField = value;
                    this.RaisePropertyChanged("RequestIdRef");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string OriginRequestIdRef {
            get {
                return this.OriginRequestIdRefField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginRequestIdRefField, value) != true)) {
                    this.OriginRequestIdRefField = value;
                    this.RaisePropertyChanged("OriginRequestIdRef");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string ServiceCode {
            get {
                return this.ServiceCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceCodeField, value) != true)) {
                    this.ServiceCodeField = value;
                    this.RaisePropertyChanged("ServiceCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string CaseNumber {
            get {
                return this.CaseNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CaseNumberField, value) != true)) {
                    this.CaseNumberField = value;
                    this.RaisePropertyChanged("CaseNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public SmevClient.SmevServiceReference.SubMessage[] SubMessages {
            get {
                return this.SubMessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.SubMessagesField, value) != true)) {
                    this.SubMessagesField = value;
                    this.RaisePropertyChanged("SubMessages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public string TestMsg {
            get {
                return this.TestMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.TestMsgField, value) != true)) {
                    this.TestMsgField = value;
                    this.RaisePropertyChanged("TestMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public string OKTMO {
            get {
                return this.OKTMOField;
            }
            set {
                if ((object.ReferenceEquals(this.OKTMOField, value) != true)) {
                    this.OKTMOField = value;
                    this.RaisePropertyChanged("OKTMO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="orgExternalType", Namespace="http://smev.gosuslugi.ru/rev120315")]
    [System.SerializableAttribute()]
    public partial class orgExternalType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TypeCodeType", Namespace="http://smev.gosuslugi.ru/rev120315")]
    public enum TypeCodeType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GSRV = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GFNC = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OTHR = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusType", Namespace="http://smev.gosuslugi.ru/rev120315")]
    public enum StatusType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        REQUEST = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RESULT = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        REJECT = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INVALID = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ACCEPT = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PING = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PROCESS = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NOTIFY = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FAILURE = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CANCEL = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        STATE = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PACKET = 11,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubMessage", Namespace="http://smev.gosuslugi.ru/rev120315")]
    [System.SerializableAttribute()]
    public partial class SubMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubRequestNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SmevClient.SmevServiceReference.StatusType StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SmevClient.SmevServiceReference.orgExternalType OriginatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestIdRefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OriginRequestIdRefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CaseNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubRequestNumber {
            get {
                return this.SubRequestNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.SubRequestNumberField, value) != true)) {
                    this.SubRequestNumberField = value;
                    this.RaisePropertyChanged("SubRequestNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public SmevClient.SmevServiceReference.StatusType Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public SmevClient.SmevServiceReference.orgExternalType Originator {
            get {
                return this.OriginatorField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginatorField, value) != true)) {
                    this.OriginatorField = value;
                    this.RaisePropertyChanged("Originator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string RequestIdRef {
            get {
                return this.RequestIdRefField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestIdRefField, value) != true)) {
                    this.RequestIdRefField = value;
                    this.RaisePropertyChanged("RequestIdRef");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string OriginRequestIdRef {
            get {
                return this.OriginRequestIdRefField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginRequestIdRefField, value) != true)) {
                    this.OriginRequestIdRefField = value;
                    this.RaisePropertyChanged("OriginRequestIdRef");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string ServiceCode {
            get {
                return this.ServiceCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceCodeField, value) != true)) {
                    this.ServiceCodeField = value;
                    this.RaisePropertyChanged("ServiceCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string CaseNumber {
            get {
                return this.CaseNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CaseNumberField, value) != true)) {
                    this.CaseNumberField = value;
                    this.RaisePropertyChanged("CaseNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageDataType", Namespace="http://smev.gosuslugi.ru/rev120315")]
    [System.SerializableAttribute()]
    public partial class MessageDataType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SmevClient.SmevServiceReference.AppDataType AppDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SmevClient.SmevServiceReference.AppDocumentType AppDocumentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SmevClient.SmevServiceReference.AppDataType AppData {
            get {
                return this.AppDataField;
            }
            set {
                if ((object.ReferenceEquals(this.AppDataField, value) != true)) {
                    this.AppDataField = value;
                    this.RaisePropertyChanged("AppData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SmevClient.SmevServiceReference.AppDocumentType AppDocument {
            get {
                return this.AppDocumentField;
            }
            set {
                if ((object.ReferenceEquals(this.AppDocumentField, value) != true)) {
                    this.AppDocumentField = value;
                    this.RaisePropertyChanged("AppDocument");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AppDataType", Namespace="http://smev.gosuslugi.ru/rev120315")]
    [System.SerializableAttribute()]
    public partial class AppDataType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SmevClient.SmevServiceReference.ArrayOfXmlElement AnyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SmevClient.SmevServiceReference.ArrayOfXmlElement Any {
            get {
                return this.AnyField;
            }
            set {
                if ((object.ReferenceEquals(this.AnyField, value) != true)) {
                    this.AnyField = value;
                    this.RaisePropertyChanged("Any");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AppDocumentType", Namespace="http://smev.gosuslugi.ru/rev120315")]
    [System.SerializableAttribute()]
    public partial class AppDocumentType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] BinaryDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestCode {
            get {
                return this.RequestCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestCodeField, value) != true)) {
                    this.RequestCodeField = value;
                    this.RaisePropertyChanged("RequestCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public byte[] BinaryData {
            get {
                return this.BinaryDataField;
            }
            set {
                if ((object.ReferenceEquals(this.BinaryDataField, value) != true)) {
                    this.BinaryDataField = value;
                    this.RaisePropertyChanged("BinaryData");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfXmlElement", Namespace="http://schemas.datacontract.org/2004/07/System.Xml", ItemName="XmlElement")]
    [System.SerializableAttribute()]
    public class ArrayOfXmlElement : System.Collections.Generic.List<System.Xml.Linq.XElement> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://smev.gosuslugi.ru/rev120315", ConfigurationName="SmevServiceReference.SmevDemoService")]
    public interface SmevDemoService {
        
        // CODEGEN: Контракт генерации сообщений с именем упаковщика (SmevDemoRequest) сообщения Request не соответствует значению по умолчанию (SampleMethod).
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.Sign, Action="http://smev.gosuslugi.ru/rev120315/SmevDemoService/SampleMethod", ReplyAction="http://smev.gosuslugi.ru/rev120315/SmevDemoService/SampleMethodResponse")]
        SmevClient.SmevServiceReference.Response SampleMethod(SmevClient.SmevServiceReference.Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SmevDemoRequest", WrapperNamespace="http://smev.gosuslugi.ru/rev120315", IsWrapped=true)]
    public partial class Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://smev.gosuslugi.ru/rev120315", Order=0)]
        public SmevClient.SmevServiceReference.MessageType Message;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://smev.gosuslugi.ru/rev120315", Order=1)]
        public SmevClient.SmevServiceReference.MessageDataType MessageData;
        
        public Request() {
        }
        
        public Request(SmevClient.SmevServiceReference.MessageType Message, SmevClient.SmevServiceReference.MessageDataType MessageData) {
            this.Message = Message;
            this.MessageData = MessageData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SmevDemoResponse", WrapperNamespace="http://smev.gosuslugi.ru/rev120315", IsWrapped=true)]
    public partial class Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://smev.gosuslugi.ru/rev120315", Order=0)]
        public SmevClient.SmevServiceReference.MessageType Message;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://smev.gosuslugi.ru/rev120315", Order=1)]
        public SmevClient.SmevServiceReference.MessageDataType MessageData;
        
        public Response() {
        }
        
        public Response(SmevClient.SmevServiceReference.MessageType Message, SmevClient.SmevServiceReference.MessageDataType MessageData) {
            this.Message = Message;
            this.MessageData = MessageData;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SmevDemoServiceChannel : SmevClient.SmevServiceReference.SmevDemoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SmevDemoServiceClient : System.ServiceModel.ClientBase<SmevClient.SmevServiceReference.SmevDemoService>, SmevClient.SmevServiceReference.SmevDemoService {
        
        public SmevDemoServiceClient() {
        }
        
        public SmevDemoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SmevDemoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmevDemoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmevDemoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmevClient.SmevServiceReference.Response SmevClient.SmevServiceReference.SmevDemoService.SampleMethod(SmevClient.SmevServiceReference.Request request) {
            return base.Channel.SampleMethod(request);
        }
        
        public void SampleMethod(ref SmevClient.SmevServiceReference.MessageType Message, ref SmevClient.SmevServiceReference.MessageDataType MessageData) {
            SmevClient.SmevServiceReference.Request inValue = new SmevClient.SmevServiceReference.Request();
            inValue.Message = Message;
            inValue.MessageData = MessageData;
            SmevClient.SmevServiceReference.Response retVal = ((SmevClient.SmevServiceReference.SmevDemoService)(this)).SampleMethod(inValue);
            Message = retVal.Message;
            MessageData = retVal.MessageData;
        }
    }
}
